name: Lint

on:
  pull_request:
  workflow_dispatch:
  merge_group:

permissions:
  contents: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Setup Ruby
        uses: ruby/setup-ruby@dffc446db9ba5a0c4446edb5bca1c5c473a806c5 # v1.235.0
        with:
          bundler-cache: true

      - name: Run linters
        uses: wearerequired/lint-action@548d8a7c4b04d3553d32ed5b6e91eb171e10e7bb # v2
        if: ${{ github.event_name == 'pull_request' }}
        with:
          auto_fix: true
          rubocop: true
          rubocop_command_prefix: bundle exec
